# version: '3.8'

# services:
#   node-app:
#     build: ./
#     ports:
#       - "3000:3000"
#     networks:
#       - monitoring

#   prometheus:
#     image: prom/prometheus:latest
#     volumes:
#       - ./:/etc/prometheus
#     ports:
#       - "9090:9090"
#     networks:
#       - monitoring

# networks:
#   monitoring:
version: '3.8'

services:
  node-app:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml   # Ensure you're mounting the correct config file
    ports:
      - "9090:9090"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
